#!/usr/bin/env bash

# Fetch JSON
json=$(curl -s ifconfig.co/json)

# Extract required fields
fields=$(echo "$json" | jq -r '{
  IP: .ip,
  Country: .country,
  City: .city,
  Region: .region_name,
  Hostname: .hostname,
  ASN: .asn,
  ASN_Org: .asn_org
} | to_entries[] | "\(.key)\t\(.value)"')

# Colors
val_color="\033[1;36m"
ip_color="\033[1;33m"
key_color="\033[0;37m"
reset="\033[0m"

echo "$fields" | while IFS=$'\t' read -r key value; do
    case $key in
      IP)
        printf "${key_color}%-10s${reset}:	${ip_color}%s${reset}\n" "$key" "$value"
        ;;
      *)
        printf "${key_color}%-10s${reset}:	${val_color}%s${reset}\n" "$key" "$value"
        ;;
    esac
done
